# Generated by Django 4.2.4 on 2023-08-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_db', '0004_postcategory_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='subscribers',
        ),
    ]
