# Generated by Django 4.2.4 on 2023-08-21 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_db', '0007_category_subscribers_delete_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
